version: '3.4'
services:
  qdrant:
    ports:
      - '6333:6333'
    volumes:
      - './qdrant_storage:/qdrant/storage:z'
    image: qdrant/qdrant
    environment:
      - QDRANT__TELEMETRY_DISABLED=true
    restart: always
  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    volumes:
      - ./bot:/bot
    env_file:
      - .env
    network_mode: host
    restart: always
volumes:
  bot:
